name: CI with Badge Update

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Jest tests with coverage
        env:
          PGUSER: postgres
          PGPASSWORD: myStrongPassword
          PGDATABASE: test_db
          PGHOST: localhost
          PGPORT: 5432
        run: npm test -- --runInBand --coverage
        working-directory: ./backend

      - name: Update README with coverage badge
        run: |
          sed -i "s/coverage-[0-9.]*%25/coverage-$(grep -oP '<span class=\"strong\">\K[0-9.]+(?=%)' ./backend/coverage/lcov-report/index.html | head -n 1)%25/g" README.md
        working-directory: ./

      - name: Check if README.md has changes
        id: readme_changed
        run: |
          if [[ $(git status --porcelain README.md) ]]; then
            echo "README.md modified"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes to README.md"
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push README with updated badge if changed
        if: env.changes == 'true'
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "docs(automated): Update coverage badge"
          git push git@github.com:julian-m-willis/spm-proj.git
