name: CI for Express.js Backend with Coverage

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: myStrongPassword
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Jest tests with coverage
        run: npm test -- --coverage
        working-directory: ./backend

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(grep -Po '^\s*lines\.*:\s*\K[0-9.]+(?=%)' ./backend/coverage/lcov-report/index.html)
          echo "::set-output name=coverage::$COVERAGE"
        working-directory: ./backend

      - name: Update README with coverage badge
        run: |
          sed -i "s/coverage-[0-9.]*%25/coverage-${{ steps.coverage.outputs.coverage }}%25/g" README.md
